### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by ghost** [romsom/a2jmidid#1]
Hi there, 
any chance you could make a release; say 8.01 with latests updates,
would like to package this but distro I use only accepts release versions.
Thank you.

**Comment by romsom** [comment]
Hi biopsin,
That's awesome!
Considering I don't hold the copyright on a2jmidid or maintain it officially and this is really just a fork to maintain it to my needs, I'm not sure if a release by me would make any difference for your distro.
Also there is actually just one commit added by me, so maybe you could just apply a patch when building the package?
Arch seems to be doing that for some other patches since the last release.
https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/a2jmidid

I tried to contact nedko and ask him whether he wants to pick up a2jmidid again, so we'll see if there will be a new release anyway in the near future :)

**Comment by ghost** [comment]
Thank's for replying romsom, I understand.
Leaving it for now as it works as intended,
sorry for the fuzz-)
